---
# tasks file for ansible-homegw-nginx
- name: add dpkg key for nginx
  become: True
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: add repository
  become: True
  apt_repository: 
    repo: deb http://nginx.org/packages/mainline/ubuntu/ xenial nginx
    state: present

- name: install essential packages for this task
  become: True
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=1200
  with_items:
    - nginx
  register: result

- name: install fast-cgi related packages 
  become: True
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=1200
  with_items:
    - fcgiwrap
    - spawn-fcgi
  when: yatest_nginx_enable_fcgiwrap
  register: result

- name: copy sample fast-cgi config file for nginx
  become: True
  copy:
    src:   "files/nginx.{{ item }}.conf"
    dest:  "/etc/nginx/conf.d/{{ item }}.conf"
    owner: "nginx"
    group: "root"
    mode:  "644"
  with_items:
    - fastcgi
    - fcgiwrap
  register: result

- name: copy sample fast-cgi default config file for nginx
  become: True
  copy:
    src:   "files/etc.default.fcgiwrap"
    dest:  "/etc/default/fcgiwrap"
    owner: "root"
    group: "root"
    mode:  "644"
  register: result

